dataset: PATTERN
model:
  num_layers: 6
  mini_layers: 1
  mlp_layers: 2
  hidden_size: 128
  use_normal_gnn: True
  pool: add
train:
  batch_size: 32
  lr_patience: 10
  epochs: 35
subgraph:
  hops: 0
  walk_length: 10
  walk_repeat: 5
  walk_p: 1.
  walk_q: 1.
  online: True

